allowBuilds:
  '@tailwindcss/oxide': true
  esbuild: true
  sharp: true
onlyBuiltDependencies:
  - '@tailwindcss/oxide'
  - esbuild
  - sharp

overrides:
  svgo@<4.1.0: 4.1.0
  js-yaml@<4.3.2: 4.3.2
  undici@<8.10.2: 8.10.2
  devalue@<5.9.3: 5.9.3